<template><h2 id="_1-mapbox地形切片简介" tabindex="-1"><a class="header-anchor" href="#_1-mapbox地形切片简介" aria-hidden="true">#</a> 1.Mapbox地形切片简介</h2>
<p>Mapbox三维地形使用位移贴图将栅格卫星影像瓦片贴到相应的地形模型上，而mapbox的地形模型通过使用tif-RGB格式的全球数字高程数据切片为png或webp瓦片生成（tif-RGB格式数据比tif-dem轻量些），这些瓦片上每个像素的RGB值通过解码为以米为单位的原始高程值，然后使用mapbox渲染贴图形成三维地形。</p>
<p><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/acf17bfc161e49d29cd3ef9596a29b90~tplv-k3u1fbpfcp-zoom-1.image" alt="在这里插入图片描述"></p>
<p>那么如有生成离线地形需求时，就可以通过在NASA上按经纬度下载相应范围的geotiff格式的dem数据，然后将tif-dem（高程灰度图）转化/编码为tif-RGB格式，然后使用相应的切片工具进行切片（按照相应mapbox相应的规范组织瓦片），而这些处理在github上已经有许多开源的处理工具，这里推荐一个集成了上面所有处理的工具（<a href="https://github.com/FreeGIS/dem2terrain" target="_blank" rel="noopener noreferrer">根据dem数据生成地形切片的工具</a>）,感兴趣的化也可以基于GDAL写一个。</p>
<p>对于Terrain-RGB的数据解码：Terrain-RGB 中每个颜色通道为 base-256，而三个颜色通道组成的为16,777,216 个值，这些值可以映射到 0.1 米的高度增量，从而实现三维地形应用所需的垂直精度，因此原来表示高程值是足够的。 mapbox收到图块后， 将需要获取各个像素的红色（R），绿色（G）和蓝色（B）值，然后根据下列公式解码为相应的高度值。</p>
<p><span class="katex-display"><span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8889em;vertical-align:-0.1944em;"></span><span class="mord mathnormal">h</span><span class="mord mathnormal">e</span><span class="mord mathnormal">i</span><span class="mord mathnormal" style="margin-right:0.03588em;">g</span><span class="mord mathnormal">h</span><span class="mord mathnormal">t</span><span class="mspace" style="margin-right:0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2778em;"></span></span><span class="base"><span class="strut" style="height:0.7278em;vertical-align:-0.0833em;"></span><span class="mord">−</span><span class="mord">10000</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mopen">((</span><span class="mord mathnormal" style="margin-right:0.00773em;">R</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">∗</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">256</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">∗</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.7278em;vertical-align:-0.0833em;"></span><span class="mord">256</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord mathnormal">G</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">∗</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.7278em;vertical-align:-0.0833em;"></span><span class="mord">256</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord mathnormal" style="margin-right:0.05017em;">B</span><span class="mclose">)</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">∗</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord">0.1</span><span class="mclose">)</span></span></span></span></span></p>
<blockquote>
<p>注：</p>
<ul>
<li>**投影：**mapbox中的地形仅支持在启用globe并且web墨卡托投影3857下使用，若原始数据dem为非3857则需先转换</li>
<li><strong>水平精度为 5 米</strong>：对于 256x256 分辨率的切片， 缩放级别到 15 级， 512x512 分辨率的切片， 缩放级别到 14 级；</li>
<li><strong>垂直精度为 0.1 米</strong>：数据以 0.1 米的高度增量进行映射；</li>
<li>**缓冲瓷砖(Buffered tiles)😗*每个地图瓦片在边缘周围包含一个1像素缓冲区，以在地形网格等用例中启用瓦片插值(也就意味着在生产瓦片时，需要将每个瓦片的像素大小-2，如在mapbox中指定瓦片大小为512x512时，实际切出来的瓦片的大小需要是514 × 514的才对)</li>
</ul>
</blockquote>
<h2 id="_2-terrain-rgb与terrain-dem" tabindex="-1"><a class="header-anchor" href="#_2-terrain-rgb与terrain-dem" aria-hidden="true">#</a> 2.Terrain-RGB与Terrain-DEM</h2>
<p>对于mapbox在线地形服务Mapbox Terrain-DEM是Mapbox Terrain-RGB在线瓦片集的优化版本，主要为更新了高程数据与数据压缩，降低了低缩放级别下的精度等来实现体积更小的瓦片，而其它的比如：地区切片生成原理、数据解码等Mapbox Terrain-DEM与Mapbox Terrain-RGB都是相同的。</p>
<p>调用在线Mapbox Terrain-RGB 示例：</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code>map.addSource('mapbox-dem'<span class="token punctuation">,</span> <span class="token punctuation">{</span>
    'type'<span class="token operator">:</span> 'raster-dem'<span class="token punctuation">,</span>
    'url'<span class="token operator">:</span> 'mapbox<span class="token operator">:</span><span class="token comment">//mapbox.terrain-rgb',</span>
    'tileSize'<span class="token operator">:</span> <span class="token number">512</span><span class="token punctuation">,</span>
    'maxzoom'<span class="token operator">:</span> <span class="token number">14</span>
<span class="token punctuation">}</span>);
map.setTerrain(<span class="token punctuation">{</span> 'source'<span class="token operator">:</span> 'mapbox-dem'<span class="token punctuation">,</span> 'exaggeration'<span class="token operator">:</span> <span class="token number">1.5</span> <span class="token punctuation">}</span>);
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>调用Mapbox在线Mapbox Terrain-DEM示例：</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code>map.addSource('mapbox-dem'<span class="token punctuation">,</span> <span class="token punctuation">{</span>
    'type'<span class="token operator">:</span> 'raster-dem'<span class="token punctuation">,</span>
    'url'<span class="token operator">:</span> 'mapbox<span class="token operator">:</span><span class="token comment">//mapbox.mapbox-terrain-dem-v1',</span>
    'tileSize'<span class="token operator">:</span> <span class="token number">512</span><span class="token punctuation">,</span>
    'maxzoom'<span class="token operator">:</span> <span class="token number">14</span>
<span class="token punctuation">}</span>);
map.setTerrain(<span class="token punctuation">{</span> 'source'<span class="token operator">:</span> 'mapbox-dem'<span class="token punctuation">,</span> 'exaggeration'<span class="token operator">:</span> <span class="token number">1.5</span> <span class="token punctuation">}</span>);
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h2 id="_3-离线地形切片实践" tabindex="-1"><a class="header-anchor" href="#_3-离线地形切片实践" aria-hidden="true">#</a> 3.离线地形切片实践</h2>
<p>此示例数据根据使用使用QGIS的SRTM-Downloader插件下载全球任意范围的dem高程数据</p>
<p><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/500dac6eff454822aa2236a005d7447a~tplv-k3u1fbpfcp-zoom-1.image" alt="请添加图片描述"></p>
<p>然后使用国内一个大佬写的mapbox地形切片工具https://github.com/FreeGIS/dem2terrain将下载的高程数据直接切片，然后使用离线调用离线mapbox地形切片</p>
<p>代码调用示例：</p>
<div class="language-vue ext-vue line-numbers-mode"><pre v-pre class="language-vue"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">'</span>map<span class="token punctuation">'</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">setup</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript">
<span class="token keyword">import</span> mapboxgl <span class="token keyword">from</span> <span class="token string">'mapbox-gl'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> onMounted<span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"vue"</span>
<span class="token function">onMounted</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span>
    <span class="token function">initmap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token keyword">const</span> <span class="token function-variable function">initmap</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span>
    mapboxgl<span class="token punctuation">.</span>accessToken <span class="token operator">=</span><span class="token string">'your token'</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> map <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">mapboxgl<span class="token punctuation">.</span>Map</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">container</span><span class="token operator">:</span> <span class="token string">'map'</span><span class="token punctuation">,</span> <span class="token comment">// </span>
        <span class="token literal-property property">style</span><span class="token operator">:</span> <span class="token string">'mapbox://styles/mapbox-map-design/ckhqrf2tz0dt119ny6azh975y'</span><span class="token punctuation">,</span>
        <span class="token literal-property property">center</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token number">110.4680</span><span class="token punctuation">,</span><span class="token number">24.4929</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token literal-property property">zoom</span><span class="token operator">:</span><span class="token number">13.1</span><span class="token punctuation">,</span>
        <span class="token literal-property property">pitch</span><span class="token operator">:</span> <span class="token number">85</span><span class="token punctuation">,</span>
        <span class="token literal-property property">bearing</span><span class="token operator">:</span> <span class="token number">80</span><span class="token punctuation">,</span>
        <span class="token literal-property property">projection</span><span class="token operator">:</span> <span class="token string">'globe'</span><span class="token punctuation">,</span>
        <span class="token comment">// worldviews:'CN'</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    map<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'load'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        map<span class="token punctuation">.</span><span class="token function">addSource</span><span class="token punctuation">(</span><span class="token string">'mapbox-dem'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span>
            <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">'raster-dem'</span><span class="token punctuation">,</span>
            <span class="token literal-property property">encoding</span><span class="token operator">:</span><span class="token string">'mapbox'</span><span class="token punctuation">,</span>
            <span class="token comment">// 注释掉官方的地形服务url，替换自己的</span>
            <span class="token comment">//'url': 'mapbox://mapbox.mapbox-terrain-dem-v1',</span>
            <span class="token comment">//使用HTTP服务器，部署静态瓦片，然后直接以xyz方式调用即可</span>
            <span class="token literal-property property">tiles</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">'http://192.168.195.128/static/{z}/{x}/{y}.png'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
            <span class="token literal-property property">tileSize</span><span class="token operator">:</span> <span class="token number">256</span><span class="token punctuation">,</span>
            <span class="token literal-property property">maxzoom</span><span class="token operator">:</span> <span class="token number">15</span><span class="token punctuation">,</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
        map<span class="token punctuation">.</span><span class="token function">setTerrain</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token string-property property">'source'</span><span class="token operator">:</span> <span class="token string">'mapbox-dem'</span><span class="token punctuation">,</span> <span class="token string-property property">'exaggeration'</span><span class="token operator">:</span> <span class="token number">2.0</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        map<span class="token punctuation">.</span><span class="token function">setFog</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
            <span class="token string-property property">'horizon-blend'</span><span class="token operator">:</span> <span class="token number">0.3</span><span class="token punctuation">,</span>
            <span class="token string-property property">'color'</span><span class="token operator">:</span> <span class="token string">'#f8f0e3'</span><span class="token punctuation">,</span>
            <span class="token string-property property">'high-color'</span><span class="token operator">:</span> <span class="token string">'#add8e6'</span><span class="token punctuation">,</span>
            <span class="token string-property property">'space-color'</span><span class="token operator">:</span> <span class="token string">'#d8f2ff'</span><span class="token punctuation">,</span>
            <span class="token string-property property">'star-intensity'</span><span class="token operator">:</span> <span class="token number">0.0</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>   
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>style</span><span class="token punctuation">></span></span><span class="token style"><span class="token language-css">
<span class="token selector">#map</span> <span class="token punctuation">{</span> 
    <span class="token property">width</span><span class="token punctuation">:</span> 1366px<span class="token punctuation">;</span>
    <span class="token property">height</span><span class="token punctuation">:</span> 722px<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>style</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br></div></div><p><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/81a358e005e34b189699b14c27c31e21~tplv-k3u1fbpfcp-zoom-1.image" alt="在这里插入图片描述"></p>
<p>下面情况为正常情况，因为其他没有rgb-dem瓦片的地方是没有高度的</p>
<p><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/9caa6ff7593347dd94b00ea4998d9e0e~tplv-k3u1fbpfcp-zoom-1.image" alt="在这里插入图片描述"></p>
<p>这里只是将地形切片进行离线化，而要将整web map进行离线化还需要将相应的卫星影像、字体、图标等进行离线化。</p>
</template>
