<template><nav class="table-of-contents"><ul><li><RouterLink to="#_1-最邻近搜索">1.最邻近搜索</RouterLink><ul><li><RouterLink to="#_1-哪些地方在x距离之内">[1]哪些地方在x距离之内</RouterLink></li><li><RouterLink to="#_2-使用st-dwithin和-distinct-on-查找最邻近位置">[2]使用ST_DWithin和 DISTINCT ON 查找最邻近位置</RouterLink></li><li><RouterLink to="#_3-带容差的相交">[3]带容差的相交</RouterLink></li><li><RouterLink to="#_4-距离范围内的地点">[4]距离范围内的地点</RouterLink></li><li><RouterLink to="#_5-使用knn距离操作符查找-n-个最近的点">[5]使用KNN距离操作符查找 N 个最近的点</RouterLink></li></ul></li><li><RouterLink to="#_2-对地理类型使用knn操作符">2.对地理类型使用KNN操作符</RouterLink><ul><li><RouterLink to="#_1-使用窗口函数对最近的n个地点进行编号">[1]使用窗口函数对最近的N个地点进行编号</RouterLink></li></ul></li><li><RouterLink to="#_3-地理注记geotagging">3.地理注记Geotagging</RouterLink><ul><li><RouterLink to="#_1-将数据标记到特定区域">[1]将数据标记到特定区域</RouterLink></li><li><RouterLink to="#_2-线性参考-将点捕捉到最近的线串">[2]线性参考：将点捕捉到最近的线串</RouterLink></li><li><RouterLink to="#_3-postgis空间聚合窗口函数">[3]PostGIS空间聚合窗口函数</RouterLink></li></ul></li></ul></nav>
<p>此文为《postgis in action3 》的学习翻译记录并做了些删减与补充</p>
<h2 id="_1-最邻近搜索" tabindex="-1"><a class="header-anchor" href="#_1-最邻近搜索" aria-hidden="true">#</a> 1.最邻近搜索</h2>
<p>这一节中主要演示常见的多种最近邻近搜索，如：</p>
<ul>
<li>位于A的X距离之内的geom有那些</li>
<li>距离A的最近的N个地方的geom有那些</li>
</ul>
<h3 id="_1-哪些地方在x距离之内" tabindex="-1"><a class="header-anchor" href="#_1-哪些地方在x距离之内" aria-hidden="true">#</a> [1]哪些地方在x距离之内</h3>
<p>可以使用 <code>ST_DWithin</code> 函数来查找彼此靠近的地点或确定一个地点是否在另一个地点的 X 单位内，还可以地理类型与几何类型混用（不过使用地理类型时是以米未单位，二使用几何类型时是空间参考系统相应的单位）</p>
<p>如下示例使用地理类型查询某点100 公里范围内的机场：</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">select</span> name<span class="token punctuation">,</span>iso_country<span class="token punctuation">,</span>iso_region
	<span class="token keyword">from</span> ch09<span class="token punctuation">.</span>airports
<span class="token keyword">where</span> ST_DWithin<span class="token punctuation">(</span>geog<span class="token punctuation">,</span>ST_Point<span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">75.0664</span><span class="token punctuation">,</span> <span class="token number">40.2003</span><span class="token punctuation">)</span>::geography<span class="token punctuation">,</span> <span class="token number">100000</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

                          name                           <span class="token operator">|</span> iso_country <span class="token operator">|</span> iso_region
<span class="token comment">---------------------------------------------------------+-------------+------------</span>
 Soaring Sun Seaplane Base                               <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Bayonne Golf Club Heliport                              <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Highlands Seaplane Base                                 <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Allen's Seaplane Base                                   <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Caven <span class="token keyword">Point</span> USAR Center Heliport                        <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Ash Personal Heliport                                   <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Picatinny Army Heliport                                 <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Morristown Medical Center Heliport                      <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Honeywell Heliport                                      <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Ballymere Heliport                                      <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Weichert Headquarters Heliport                          <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Fla<span class="token operator">-</span>Net Airport                                         <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Trinca Airport                                          <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Cherry Hill Heliport                                    <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Newton Airport                                          <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Scheller Airport                                        <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Newton Memorial Hospital Heliport                       <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Colgate<span class="token operator">-</span>Palmolive<span class="token operator">/</span>Mennen Heliport                       <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Weiss Farm Airport                                      <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Mianecki Heliport                                       <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Aeroflex<span class="token operator">-</span>Andover Airport                                <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Hudson Farm West Heliport                               <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Hackettstown Community Hospital Heliport                <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Hackettstown Hospital Heliport                          <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Florham Park Heliport                                   <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Soverel Park Heliport                                   <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Newark Academy Heliport                                 <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
<span class="token comment">-- More  --</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br></div></div><p>[2]使用ST_DWithin和ST_Distance进行最邻近搜索</p>
<p>可以通过修改（添加使用ST_Distance函数）上面的示例来实现查询结果按距离排序</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">SELECT</span> ident<span class="token punctuation">,</span> name
<span class="token keyword">FROM</span> 
	ch09<span class="token punctuation">.</span>airports
	<span class="token keyword">CROSS</span> <span class="token keyword">JOIN</span> <span class="token comment">-- 笛卡尔积交叉连接</span>
	<span class="token punctuation">(</span><span class="token keyword">SELECT</span> ST_Point<span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">75.0664</span><span class="token punctuation">,</span> <span class="token number">40.2003</span><span class="token punctuation">)</span>::geography <span class="token keyword">AS</span> ref_geog<span class="token punctuation">)</span> <span class="token keyword">As</span> r
<span class="token keyword">WHERE</span> ST_DWithin<span class="token punctuation">(</span>geog<span class="token punctuation">,</span> ref_geog<span class="token punctuation">,</span> <span class="token number">100000</span><span class="token punctuation">)</span>
<span class="token keyword">ORDER</span> <span class="token keyword">BY</span> ST_Distance<span class="token punctuation">(</span>geog<span class="token punctuation">,</span> ref_geog<span class="token punctuation">)</span> <span class="token comment">-- 根据已知点距离查询点的距离来排序</span>
<span class="token keyword">LIMIT</span> <span class="token number">5</span><span class="token punctuation">;</span> <span class="token comment">-- 返回前5个结果</span>

ident <span class="token operator">|</span>                name
<span class="token comment">-------+-------------------------------------</span>
 KNJP  <span class="token operator">|</span> Warminster Naval Air Warfare Center
 <span class="token number">31</span>PN  <span class="token operator">|</span> Control Dynamics Heliport
 PS84  <span class="token operator">|</span> Warminster Hospital Heliport
 <span class="token number">5</span>PN7  <span class="token operator">|</span> Jarrett Airport
 <span class="token number">5</span>PN4  <span class="token operator">|</span> Mahon Heliport
<span class="token punctuation">(</span><span class="token number">5</span> 行记录<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><h3 id="_2-使用st-dwithin和-distinct-on-查找最邻近位置" tabindex="-1"><a class="header-anchor" href="#_2-使用st-dwithin和-distinct-on-查找最邻近位置" aria-hidden="true">#</a> [2]使用ST_DWithin和 DISTINCT ON 查找最邻近位置</h3>
<p>还有一种常见的情况是：从一组地点开始，查找距离另一组地点最近的地点（套了个娃😓，不过在现实生活中还是挺常见的需求），举个例子：在一个主要城市的所有疗养院 10 英里范围内有多少紧急医疗中心。</p>
<p>对于这种情况可以使用组合 <code>ST_DWithin</code> 和 PostgreSQL <code>DISTINCT ON</code> 来实现搜索（ DISTINCT ON 执行隐式 GROUP BY，但不限于仅返回您分组的字段）</p>
<p>例如：以下查询查找离每个机场最近的导航工具（交通站点）</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">SELECT</span> <span class="token keyword">DISTINCT</span> <span class="token keyword">ON</span> <span class="token punctuation">(</span>a<span class="token punctuation">.</span>ident<span class="token punctuation">)</span>   <span class="token comment">-- 对机场去重+排序，以保留实现最近的一个导航工具</span>
	a<span class="token punctuation">.</span>ident<span class="token punctuation">,</span> a<span class="token punctuation">.</span>name <span class="token keyword">As</span> airport<span class="token punctuation">,</span> n<span class="token punctuation">.</span>name <span class="token keyword">As</span> closest_navaid<span class="token punctuation">,</span>
<span class="token punctuation">(</span>ST_Distance<span class="token punctuation">(</span>a<span class="token punctuation">.</span>geog<span class="token punctuation">,</span>n<span class="token punctuation">.</span>geog<span class="token punctuation">)</span><span class="token operator">/</span><span class="token number">1000</span><span class="token punctuation">)</span>::<span class="token keyword">integer</span> <span class="token keyword">As</span> dist_km
<span class="token keyword">FROM</span> ch09<span class="token punctuation">.</span>airports <span class="token keyword">As</span> a <span class="token keyword">LEFT</span> <span class="token keyword">JOIN</span> ch09<span class="token punctuation">.</span>navaids <span class="token keyword">As</span> n <span class="token comment">-- 左连接（以左为基准）</span>
<span class="token keyword">ON</span> ST_DWithin<span class="token punctuation">(</span>a<span class="token punctuation">.</span>geog<span class="token punctuation">,</span> n<span class="token punctuation">.</span>geog<span class="token punctuation">,</span><span class="token number">100000</span><span class="token punctuation">)</span> <span class="token comment">-- 距离机场100公里范围内最近的导航工具       </span>
<span class="token keyword">ORDER</span> <span class="token keyword">BY</span> a<span class="token punctuation">.</span>ident<span class="token punctuation">,</span> dist_km<span class="token punctuation">;</span>

ident <span class="token operator">|</span> airport <span class="token operator">|</span> closest_navaid <span class="token operator">|</span> dist_km
<span class="token comment">-------+---------------------------+--------------------+---------</span>
<span class="token number">00</span>A <span class="token operator">|</span> Total RF Heliport <span class="token operator">|</span> North Philadelphia <span class="token operator">|</span> <span class="token number">7</span>
<span class="token number">00</span>AK <span class="token operator">|</span> Lowell Field <span class="token operator">|</span> Homer <span class="token operator">|</span> <span class="token number">30</span>
<span class="token number">00</span>AL <span class="token operator">|</span> Epps Airpark <span class="token operator">|</span> Capshaw <span class="token operator">|</span> <span class="token number">10</span>
<span class="token number">00</span>AR <span class="token operator">|</span> Newport Hospital <span class="token operator">|</span> Newport <span class="token operator">|</span> <span class="token number">8</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><blockquote>
<p>其查找的圆半径越慢，这里查询进入用了4秒多。。。</p>
<p>此查询使用左连接而不是内连接，以确保即使在没有找到导航设备时，查询操作仍然继续进行</p>
</blockquote>
<h3 id="_3-带容差的相交" tabindex="-1"><a class="header-anchor" href="#_3-带容差的相交" aria-hidden="true">#</a> [3]带容差的相交</h3>
<p>还可以使用ST_DWithin来代替ST_Intersects判断相交关系，其优势有：</p>
<p>当有两个几何因有效位数引起的差异而无法相交时，可以使用<code>ST_DWithin</code>检查相交。例子（忽略0.0001内的容差）：</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">SELECT</span> ST_DWithin<span class="token punctuation">(</span>
	ST_GeomFromText<span class="token punctuation">(</span>
		<span class="token string">'LINESTRING(1 2, 3 4)'</span>
	<span class="token punctuation">)</span><span class="token punctuation">,</span>
	ST_Point<span class="token punctuation">(</span><span class="token number">3.00001</span><span class="token punctuation">,</span> <span class="token number">4.000001</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
	<span class="token number">0.0001</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>

 st_dwithin
<span class="token comment">------------</span>
 <span class="token boolean">true</span>
<span class="token punctuation">(</span><span class="token number">1</span> 行记录<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><p>在使用实际的数据时通常会使用带容差的相交，而并非所有数据都完美对齐</p>
<p>使用 <code>ST_DWithin</code> 代替 <code>ST_Intersects</code> 还有一个优势：<code>ST_DWithin</code> 不会像 <code>ST_Intersects</code> 那样经常因为无效几何图形而被阻碍过程，尤其是在几何图形具有自相交区域的情况下。 <code>ST_DWithin</code> 不关心有效性，因为它不依赖于交集矩阵（九交）。</p>
<h3 id="_4-距离范围内的地点" tabindex="-1"><a class="header-anchor" href="#_4-距离范围内的地点" aria-hidden="true">#</a> [4]距离范围内的地点</h3>
<p>有时候还会有一种情况，当在查询在某些距离范围内的地点（圆环范围）</p>
<p>这时就需要调用两个<code>ST_DWithin</code>来实现了，其主要原理为使用两个<code>ST_DWithin</code>查询俩个范围（一大一小），只要保留大的范围减去小的范围即可。具体示例如下（还是机场表）：</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">SELECT</span> name<span class="token punctuation">,</span> iso_country<span class="token punctuation">,</span> iso_region
<span class="token keyword">FROM</span> ch09<span class="token punctuation">.</span>airports
<span class="token keyword">WHERE</span> ST_DWithin<span class="token punctuation">(</span>geog<span class="token punctuation">,</span> 
		ST_Point<span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">75.0664</span><span class="token punctuation">,</span> <span class="token number">40.2003</span><span class="token punctuation">)</span>::geography<span class="token punctuation">,</span> <span class="token number">100000</span><span class="token punctuation">)</span> <span class="token comment">-- 100公里范围内的机场</span>
	<span class="token operator">AND</span> <span class="token operator">NOT</span> ST_DWithin<span class="token punctuation">(</span>geog<span class="token punctuation">,</span>
		ST_Point<span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">75.0664</span><span class="token punctuation">,</span> <span class="token number">40.2003</span><span class="token punctuation">)</span>::geography<span class="token punctuation">,</span> <span class="token number">90000</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">-- 90公里内的机场</span>
		
                          name                           <span class="token operator">|</span> iso_country <span class="token operator">|</span> iso_region
<span class="token comment">---------------------------------------------------------+-------------+------------</span>
 Soaring Sun Seaplane Base                               <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Bayonne Golf Club Heliport                              <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Highlands Seaplane Base                                 <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Caven <span class="token keyword">Point</span> USAR Center Heliport                        <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Ash Personal Heliport                                   <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Picatinny Army Heliport                                 <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Weichert Headquarters Heliport                          <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Cherry Hill Heliport                                    <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Newton Airport                                          <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Newton Memorial Hospital Heliport                       <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Mianecki Heliport                                       <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Aeroflex<span class="token operator">-</span>Andover Airport                                <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Hudson Farm West Heliport                               <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Soverel Park Heliport                                   <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Kennedy Stadium Heliport                                <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 Smoketown Airport                                       <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>PA
 Hideaway Ultralightport                                 <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>PA
 Chem<span class="token operator">-</span>Fleur Helistop                                     <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 University Hospital Rooftop Heliport                    <span class="token operator">|</span> US          <span class="token operator">|</span> US<span class="token operator">-</span>NJ
 <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br></div></div><h3 id="_5-使用knn距离操作符查找-n-个最近的点" tabindex="-1"><a class="header-anchor" href="#_5-使用knn距离操作符查找-n-个最近的点" aria-hidden="true">#</a> [5]使用KNN距离操作符查找 N 个最近的点</h3>
<p>postgis有关于最邻近搜索（K-nearest neighbor）的两个操作符：</p>
<ul>
<li><code>&lt;-&gt;</code> - 这是几何geometry和地理geography的 KNN 距离操作符， <code>A &lt;-&gt; B</code> 返回两个几何图形 A 和 B 之间的距离</li>
<li><code>&lt;#&gt;</code> - 这是几何geometry的 KNN 边界框距离操作符， <code>A &lt;#&gt; B</code> 返回 A 和 B 的边界框之间的最小距离</li>
</ul>
<blockquote>
<p>使用 <code>&lt;-&gt;</code> 时，两个对象必须都是几何图形或两者都是地理类型，如果与地理进行比较，经度/纬度空间参考系统中的几何图形将自动转换为地理；如果几何图形使用非 lon/lat 空间参考系统，则会出现错误</p>
<p>KNN 运算符的行为与常用的重叠运算符 (&amp;&amp;)、ST_Intersects 和其他关系函数非常不同。 KNN 运算符只能在 ORDER BY 子句中使用空间索引，并且当运算符中一侧的对象在查询或子查询的整个生命周期内保持不变时。人们常犯的一个错误是尝试在 WHERE 子句中使用 KNN 运算符，并想知道为什么它们没有获得任何索引速度提升。 KNN 运算符也总是返回数值。这与 &amp;&amp;、ST_Intersects 和其他关系函数不同，它们仅在 WHERE 和 JOIN 子句中使用空间索引，并返回布尔值 true/false</p>
</blockquote>
<p>因为 KNN 运算符会输出的是距离，该距离通常还是需要在查询中使用的，因此推荐在 SELECT 子句中使用别名定义它们。在 ORDER BY 子句中使用定义的别名而不是在 ORDER BY 子句中再次重复整个 &lt;-&gt; 时，是仍然可以获得相同的索引提升的</p>
<p>如使用空间索引和别名的最基本的 KNN 示例（离点最近的十个几何图形）：</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">SELECT</span>
	pid<span class="token punctuation">,</span>
	geom
	<span class="token operator">&lt;</span><span class="token operator">-</span><span class="token operator">></span>  <span class="token comment">--  return geom 与 point的距离</span>
	ST_Transform<span class="token punctuation">(</span>
		ST_SetSRID<span class="token punctuation">(</span>ST_Point<span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">71.09368</span><span class="token punctuation">,</span> <span class="token number">42.35857</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token number">4326</span><span class="token punctuation">)</span>
		<span class="token punctuation">,</span><span class="token number">26986</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> dist  
<span class="token keyword">FROM</span> ch09<span class="token punctuation">.</span>land
<span class="token keyword">WHERE</span> land_type <span class="token operator">=</span> <span class="token string">'apartment'</span>
<span class="token keyword">ORDER</span> <span class="token keyword">BY</span> dist <span class="token comment">-- 按距离从小到大排序      </span>
<span class="token keyword">LIMIT</span> <span class="token number">10</span><span class="token punctuation">;</span>

pid   <span class="token operator">|</span>       dist
<span class="token comment">--------+-------------------</span>
 <span class="token number">68</span><span class="token operator">-</span><span class="token number">74</span>  <span class="token operator">|</span> <span class="token number">577.6971291679585</span>
 <span class="token number">48</span><span class="token operator">-</span><span class="token number">154</span> <span class="token operator">|</span> <span class="token number">606.4853088634092</span>
 <span class="token number">74</span><span class="token operator">-</span><span class="token number">3</span>   <span class="token operator">|</span> <span class="token number">636.3831678954274</span>
 <span class="token number">70</span><span class="token operator">-</span><span class="token number">98</span>  <span class="token operator">|</span> <span class="token number">636.8056504490122</span>
 <span class="token number">44</span><span class="token operator">-</span><span class="token number">107</span> <span class="token operator">|</span> <span class="token number">653.9337102092323</span>
 <span class="token number">74</span><span class="token operator">-</span><span class="token number">24</span>  <span class="token operator">|</span> <span class="token number">670.4939392784329</span>
 <span class="token number">70</span><span class="token operator">-</span><span class="token number">97</span>  <span class="token operator">|</span> <span class="token number">680.0793327608731</span>
 <span class="token number">92</span><span class="token operator">-</span><span class="token number">118</span> <span class="token operator">|</span> <span class="token number">693.2394869664229</span>
 <span class="token number">75</span><span class="token operator">-</span><span class="token number">45</span>  <span class="token operator">|</span> <span class="token number">699.7823017007512</span>
 <span class="token number">42</span><span class="token operator">-</span><span class="token number">68</span>  <span class="token operator">|</span> <span class="token number">719.1473197030103</span>
<span class="token punctuation">(</span><span class="token number">10</span> 行记录<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br></div></div><blockquote>
<p>与其他操作符与函数一样，两个几何的空间参考系统需要是一样的</p>
</blockquote>
<h2 id="_2-对地理类型使用knn操作符" tabindex="-1"><a class="header-anchor" href="#_2-对地理类型使用knn操作符" aria-hidden="true">#</a> 2.对地理类型使用KNN操作符</h2>
<p>对于地理类型，KNN操作符的使用与几何类型类似：</p>
<p>例如：查看距离Boston Logan（一个机场名）最近的十个机场：</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">SELECT</span> ident<span class="token punctuation">,</span> name<span class="token punctuation">,</span>
	geog <span class="token operator">&lt;</span><span class="token operator">-</span><span class="token operator">></span> <span class="token punctuation">(</span><span class="token keyword">SELECT</span> geog
				<span class="token keyword">FROM</span> ch09<span class="token punctuation">.</span>airports <span class="token keyword">WHERE</span> ident <span class="token operator">=</span> <span class="token string">'KBOS'</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> dist <span class="token comment">-- Boston Logan坐标</span>
<span class="token keyword">FROM</span> ch09<span class="token punctuation">.</span>airports
<span class="token keyword">WHERE</span> ident <span class="token operator">!=</span> <span class="token string">'KBOS'</span> <span class="token operator">AND</span> <span class="token keyword">type</span> <span class="token operator">=</span> <span class="token string">'large_airport'</span> <span class="token comment">-- 不包括Boston Logan的大型机场</span>
<span class="token keyword">ORDER</span> <span class="token keyword">BY</span> dist 
<span class="token keyword">LIMIT</span> <span class="token number">10</span><span class="token punctuation">;</span>
 ident <span class="token operator">|</span>                          name                           <span class="token operator">|</span>        dist
<span class="token comment">-------+---------------------------------------------------------+--------------------</span>
 KMHT  <span class="token operator">|</span> Manchester<span class="token operator">-</span>Boston Regional Airport                      <span class="token operator">|</span>  <span class="token number">72338.42343183087</span>
 KPVD  <span class="token operator">|</span> Theodore Francis Green State Airport                    <span class="token operator">|</span>  <span class="token number">78161.53094166022</span>
 KBDL  <span class="token operator">|</span> Bradley International Airport                           <span class="token operator">|</span>  <span class="token number">146189.5781946512</span>
 KPWM  <span class="token operator">|</span> Portland International Jetport                          <span class="token operator">|</span>  <span class="token number">153360.8589790108</span>
 KLGA  <span class="token operator">|</span> La Guardia Airport                                      <span class="token operator">|</span>  <span class="token number">296692.4314658076</span>
 KJFK  <span class="token operator">|</span> John F Kennedy International Airport                    <span class="token operator">|</span> <span class="token number">300178.39036616695</span>
 KEWR  <span class="token operator">|</span> Newark Liberty International Airport                    <span class="token operator">|</span>  <span class="token number">322306.6233001464</span>
 KBGR  <span class="token operator">|</span> Bangor International Airport                            <span class="token operator">|</span> <span class="token number">323308.49386454397</span>
 CYUL  <span class="token operator">|</span> Montreal <span class="token operator">/</span> Pierre Elliott Trudeau International Airport <span class="token operator">|</span>  <span class="token number">408984.0780492237</span>
 KSYR  <span class="token operator">|</span> Syracuse Hancock International Airport                  <span class="token operator">|</span>   <span class="token number">424727.654195591</span>
<span class="token punctuation">(</span><span class="token number">10</span> 行记录<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br></div></div><h3 id="_1-使用窗口函数对最近的n个地点进行编号" tabindex="-1"><a class="header-anchor" href="#_1-使用窗口函数对最近的n个地点进行编号" aria-hidden="true">#</a> [1]使用窗口函数对最近的N个地点进行编号</h3>
<p>在前面的示例中仅仅对查询的最邻近的地点进行了排序，并没有对其进行排序，有时候对其进行编号也是很有用的。</p>
<p>这时便可以使用 <code>row_number()</code>, <code>rank()</code>, <code>dense_rank()</code>等窗口函数对行进行编号了，窗口函数（也叫OLAP函数（Online Anallytical Processing，联机分析处理）是一种可以查看查询的整个数据集并提供与其在数据中的位置相关的信息的函数。</p>
<p>窗口函数语法：</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">select</span> <span class="token operator">&lt;</span>窗口函数<span class="token operator">></span> <span class="token keyword">over</span> <span class="token punctuation">(</span><span class="token keyword">partition</span> <span class="token keyword">by</span> <span class="token operator">&lt;</span>用于分组的列名<span class="token operator">></span>
                <span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token operator">&lt;</span>用于排序的列名<span class="token operator">></span> <span class="token punctuation">)</span>  <span class="token comment">-- 默认为asc</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>示例：（查询每所学校 100 米范围内的道路，并根据道路距学校的距离对这些道路进行编号）</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">SELECT</span> 
    pid<span class="token punctuation">,</span> rnum<span class="token punctuation">,</span>  <span class="token comment">-- pid为学校的唯一标识符</span>
	rank<span class="token punctuation">,</span> drank<span class="token punctuation">,</span>
	road_name<span class="token punctuation">,</span> 
    <span class="token function">round</span><span class="token punctuation">(</span>CAST<span class="token punctuation">(</span>dist_km <span class="token keyword">As</span> <span class="token keyword">numeric</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token number">2</span><span class="token punctuation">)</span> <span class="token keyword">As</span> dist_km
<span class="token keyword">FROM</span> <span class="token punctuation">(</span>
    <span class="token keyword">SELECT</span> 
        ROW_NUMBER<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">OVER</span> w_dist <span class="token keyword">As</span> rnum<span class="token punctuation">,</span> 
	    RANK<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">OVER</span> w_dist <span class="token keyword">AS</span> rank<span class="token punctuation">,</span> 
	    DENSE_RANK<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">OVER</span> w_dist <span class="token keyword">AS</span> drank<span class="token punctuation">,</span> <span class="token comment">-- 不同窗口函数</span>
		E<span class="token punctuation">.</span>pid<span class="token punctuation">,</span> E<span class="token punctuation">.</span>road_name<span class="token punctuation">,</span> 
		E<span class="token punctuation">.</span>dist_km
    <span class="token keyword">FROM</span> 
		<span class="token punctuation">(</span><span class="token keyword">SELECT</span> l<span class="token punctuation">.</span>pid<span class="token punctuation">,</span>  
          <span class="token function">round</span><span class="token punctuation">(</span><span class="token punctuation">(</span>r<span class="token punctuation">.</span>geom <span class="token operator">&lt;</span><span class="token operator">-</span><span class="token operator">></span> l<span class="token punctuation">.</span>geom<span class="token punctuation">)</span>::<span class="token keyword">numeric</span><span class="token operator">/</span><span class="token number">1000</span><span class="token punctuation">,</span><span class="token number">2</span><span class="token punctuation">)</span> <span class="token keyword">As</span> dist_km
		 <span class="token keyword">FROM</span> ch09<span class="token punctuation">.</span>land <span class="token keyword">As</span> l <span class="token comment">-- 地点表</span>
	<span class="token keyword">LEFT</span> <span class="token keyword">JOIN</span> <span class="token comment">-- 即使在 100 米范围内没有道路，也可以输出学校信息</span>
        ch09<span class="token punctuation">.</span>road <span class="token keyword">As</span> r <span class="token comment">-- 道路表</span>
	<span class="token keyword">ON</span> ST_DWithin<span class="token punctuation">(</span>r<span class="token punctuation">.</span>geom<span class="token punctuation">,</span>l<span class="token punctuation">.</span>geom<span class="token punctuation">,</span><span class="token number">100</span><span class="token punctuation">)</span> 
	<span class="token keyword">WHERE</span> l<span class="token punctuation">.</span>land_type <span class="token operator">=</span> <span class="token string">'education'</span>
		<span class="token operator">AND</span> l<span class="token punctuation">.</span>pid <span class="token operator">LIKE</span> <span class="token string">'143-1%'</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> E
	WINDOW w_dist <span class="token keyword">AS</span> <span class="token punctuation">(</span><span class="token keyword">PARTITION</span> <span class="token keyword">BY</span> E<span class="token punctuation">.</span>pid <span class="token keyword">ORDER</span> <span class="token keyword">BY</span> e<span class="token punctuation">.</span>dist_km<span class="token punctuation">)</span> <span class="token comment">-- 定义要在 OVER 中使用的 WINDOW 子句</span>
<span class="token punctuation">)</span> <span class="token keyword">As</span> X
<span class="token keyword">WHERE</span> X<span class="token punctuation">.</span>drank <span class="token operator">&lt;</span> <span class="token number">3</span> <span class="token comment">-- 仅返回2条最近的道路</span>
<span class="token keyword">ORDER</span> <span class="token keyword">BY</span> pid<span class="token punctuation">,</span> rnum<span class="token punctuation">;</span>

pid <span class="token operator">|</span> rnum <span class="token operator">|</span> rank <span class="token operator">|</span> drank <span class="token operator">|</span> road_name <span class="token operator">|</span> dist_km
<span class="token comment">--------+------+------+-------+------------------+---------</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">10</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> CAMBRIDGE STREET <span class="token operator">|</span> <span class="token number">0.01</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">11</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> CAMBRIDGE STREET <span class="token operator">|</span> <span class="token number">0.01</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">11</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> QUINCY STREET <span class="token operator">|</span> <span class="token number">0.06</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">11</span> <span class="token operator">|</span> <span class="token number">3</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> CAMBRIDGE STREET <span class="token operator">|</span> <span class="token number">0.06</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">11</span> <span class="token operator">|</span> <span class="token number">4</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> CAMBRIDGE STREET <span class="token operator">|</span> <span class="token number">0.06</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">13</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> KIRKLAND STREET <span class="token operator">|</span> <span class="token number">0.01</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">13</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> QUINCY STREET <span class="token operator">|</span> <span class="token number">0.07</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">15</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> CAMBRIDGE STREET <span class="token operator">|</span> <span class="token number">0.06</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">15</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> KIRKLAND STREET <span class="token operator">|</span> <span class="token number">0.09</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">17</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> CAMBRIDGE STREET <span class="token operator">|</span> <span class="token number">0.01</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">17</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> <span class="token number">1</span> <span class="token operator">|</span> QUINCY STREET <span class="token operator">|</span> <span class="token number">0.01</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">17</span> <span class="token operator">|</span> <span class="token number">3</span> <span class="token operator">|</span> <span class="token number">3</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> BROADWAY <span class="token operator">|</span> <span class="token number">0.02</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">17</span> <span class="token operator">|</span> <span class="token number">4</span> <span class="token operator">|</span> <span class="token number">3</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> KIRKLAND STREET <span class="token operator">|</span> <span class="token number">0.02</span>
<span class="token number">143</span><span class="token operator">-</span><span class="token number">17</span> <span class="token operator">|</span> <span class="token number">5</span> <span class="token operator">|</span> <span class="token number">3</span> <span class="token operator">|</span> <span class="token number">2</span> <span class="token operator">|</span> CAMBRIDGE STREET <span class="token operator">|</span> <span class="token number">0.02</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br></div></div><p>对于结果的观察可以发现这几个窗口函数带来的便利：</p>
<ul>
<li><code>row_number()</code>:对返回的结果中按照某一行创建一个字段来存储排序序号（如上<code>rnum</code>，partition by pid）</li>
<li><code>rank()</code>：实际上是对row_number的扩展吧，把dist_km中相同的并为同一个排序号</li>
<li><code>dense_rank()</code> :对<code>rank()</code>的在扩展，如上面143-17，的rank和drank列就可以发现<code>dense_rank()</code>是对<code>rank()</code>合并后的行进行再排序。</li>
</ul>
<h2 id="_3-地理注记geotagging" tabindex="-1"><a class="header-anchor" href="#_3-地理注记geotagging" aria-hidden="true">#</a> 3.地理注记Geotagging</h2>
<p>地理标记是指一类空间技术，这通常有两种形式：</p>
<ul>
<li><strong>区域标记</strong>：使用一个注记来标注一个几何体（例如使用区域的名称（州、市）来标注一个几何体）</li>
<li><strong>线性参考</strong>：对线使用的一种标记</li>
</ul>
<p>区域标记和线性参考是GIS空间分析冲常用的技术，例如，假设你有一个加利福尼亚州所有麦当劳店的列表，并且你有一个所有县的表作为几何图形。区域地理注记可以尝试找出哪些县包含哪些麦当劳，以便你可以轻松获得每个县的麦当劳数量。相反，如果你有加利福尼亚州所有主要高速公路的列表，则线性参考可以找出哪些高速公路在路边有哪些麦当劳店（这只是使用线性参考的一种情况，更多常见的情况https://www.jianshu.com/p/4916b85bea65）</p>
<h3 id="_1-将数据标记到特定区域" tabindex="-1"><a class="header-anchor" href="#_1-将数据标记到特定区域" aria-hidden="true">#</a> [1]将数据标记到特定区域</h3>
<p>空间数据库更常见的用途之一是标记区域。通常，您会将空间区域命名为多边形或多多边形。这些可能是政治区、销售区、市或其他任何地方。</p>
<p>下面看一个基于 airports 表的示例。加入你想要查找并存储所有机场的时区。而时区区域将表为多面体表 (ch09.tz_world)，那么对于每个机场，需要先根据机场的坐标找到它所在的时区多面体，并将其时区设置为该区域的时区值。以下示例使用相应时区多面体中的时区值更新机场的时区字段</p>
<p><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/5513ffe4234f4a55bf67dd54d72f4ddf~tplv-k3u1fbpfcp-zoom-1.image" alt="在这里插入图片描述"></p>
<blockquote>
<p>ch09.tz_world</p>
</blockquote>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">ALTER</span> <span class="token keyword">TABLE</span> ch09<span class="token punctuation">.</span>airports <span class="token keyword">ADD</span> <span class="token keyword">COLUMN</span> <span class="token keyword">IF</span> <span class="token operator">NOT</span> <span class="token keyword">EXISTS</span> tz <span class="token keyword">varchar</span><span class="token punctuation">(</span><span class="token number">30</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">-- 添加一个时区列</span>
<span class="token keyword">UPDATE</span> ch09<span class="token punctuation">.</span>airports
<span class="token keyword">SET</span> tz <span class="token operator">=</span> t<span class="token punctuation">.</span>tzid
<span class="token keyword">FROM</span> ch09<span class="token punctuation">.</span>tz_world <span class="token keyword">As</span> t
<span class="token keyword">WHERE</span> ST_Intersects<span class="token punctuation">(</span>ch09<span class="token punctuation">.</span>airports<span class="token punctuation">.</span>geog<span class="token punctuation">,</span> t<span class="token punctuation">.</span>geog<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">-- 机场点于时区多边形相交处</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p>这样，要显示每个机场的当前本地时间的，就可以直接使用内置的 PostgreSQL 时区函数与根据您tz列指定的时区来计算了</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>SELECT ident, name, CURRENT_TIMESTAMP AT TIME ZONE tz AS ts_at_airport
FROM ch09.airports
WHERE ident IN('KBOS','KSAN','LIRF','OMDB','ZLXY');
 ident |                        name                         |       ts_at_airport
-------+-----------------------------------------------------+----------------------------
 KBOS  | General Edward Lawrence Logan International Airport | 2022-11-15 00:54:41.464544
 KSAN  | San Diego International Airport                     | 2022-11-14 21:54:41.464544
 LIRF  | Leonardo da Vinci–Fiumicino Airport                | 2022-11-15 06:54:41.464544
 OMDB  | Dubai International Airport                         | 2022-11-15 09:54:41.464544
 ZLXY  | Xi'an Xianyang International Airport                | 2022-11-15 13:54:41.464544
(5 行记录)
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h3 id="_2-线性参考-将点捕捉到最近的线串" tabindex="-1"><a class="header-anchor" href="#_2-线性参考-将点捕捉到最近的线串" aria-hidden="true">#</a> [2]线性参考：将点捕捉到最近的线串</h3>
<p>一种常见的线性参考形式为将最近线串上的最近点返回到参考点。这种线性参考通常被称为捕捉点到最近的线串。从一组点和一组线串开始尝试将每个点与其最近的线串相关联，然后与该线串上的最近点相关联</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">SELECT</span> <span class="token keyword">DISTINCT</span> <span class="token keyword">ON</span> <span class="token punctuation">(</span>p<span class="token punctuation">.</span>pid<span class="token punctuation">)</span>  <span class="token comment">-- 只保留最近的地块和道路对</span>
    p<span class="token punctuation">.</span>addr_num <span class="token operator">||</span> <span class="token string">' '</span> <span class="token operator">||</span> full_str <span class="token keyword">AS</span> parcel<span class="token punctuation">,</span> 
    r<span class="token punctuation">.</span>road_name <span class="token keyword">AS</span> road<span class="token punctuation">,</span>
    ST_ClosestPoint<span class="token punctuation">(</span>p<span class="token punctuation">.</span>geom<span class="token punctuation">,</span>r<span class="token punctuation">.</span>geom<span class="token punctuation">)</span> <span class="token keyword">As</span> snapped_point <span class="token comment">-- return点到直线最近的点（直线上）</span>
<span class="token keyword">FROM</span> ch09<span class="token punctuation">.</span>land <span class="token keyword">AS</span> p <span class="token keyword">INNER</span> <span class="token keyword">JOIN</span> ch09<span class="token punctuation">.</span>road <span class="token keyword">AS</span> r
<span class="token keyword">ON</span> ST_DWithin<span class="token punctuation">(</span>p<span class="token punctuation">.</span>geom<span class="token punctuation">,</span>r<span class="token punctuation">.</span>geom<span class="token punctuation">,</span><span class="token number">20.0</span><span class="token punctuation">)</span> <span class="token comment">-- 仅在land与road20米范围内生成</span>
<span class="token keyword">ORDER</span> <span class="token keyword">BY</span> p<span class="token punctuation">.</span>pid<span class="token punctuation">,</span> ST_Distance<span class="token punctuation">(</span>p<span class="token punctuation">.</span>geom<span class="token punctuation">,</span>r<span class="token punctuation">.</span>geom<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/30874ef63b3642f198854ddfc350be06~tplv-k3u1fbpfcp-zoom-1.image" alt="在这里插入图片描述"></p>
<p><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/668a167e6f3c4525830bd2f854c345d4~tplv-k3u1fbpfcp-zoom-1.image" alt="在这里插入图片描述">
<img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/7b3998c0b19a4b52ae3a19320e3b7ee6~tplv-k3u1fbpfcp-zoom-1.image" alt="在这里插入图片描述"></p>
<blockquote>
<p><code>ST_ClosestPoint(geometry A, geometry B)</code>：在点与线串之间的最接近是点本身，但是在线条和点之间的最接近的点是线字符串上最接近的点。</p>
<p>其他情况，则是多边形A到多边形B上最近的点（生成）</p>
</blockquote>
<h3 id="_3-postgis空间聚合窗口函数" tabindex="-1"><a class="header-anchor" href="#_3-postgis空间聚合窗口函数" aria-hidden="true">#</a> [3]PostGIS空间聚合窗口函数</h3>
<p>PostGIS 2.3 推出了第一个特定于 PostGIS 的窗口函数：<code>ST_ClusterDBSCAN</code> 和 <code>ST_ClusterKMeans</code></p>
<p>这些空间聚合窗口函数可以根据几何对象彼此的接近程度将它们聚集在一起。</p>
<p>这里举一个示例：假如现在有一批医护人员要根据地址对需要的人进行疫苗注册，那么确保给他们分配的地址数量均匀且不会太离散。这时就可以发挥postgis空间聚合函数的作用了，它可以将数据集划分为多个块，其中每个块代表一组接近程度高的事物。该窗口函数返回簇号（cluster  number），具有相同族号的记录将代表应分配给特定员工的一批地址</p>
<ul>
<li><code>integer ST_ClusterKMeans(geometry geom_of_clusters, integer number_of_clusters);</code> 需要传入将数据分成的聚类数量，它会使用此数量根据与集合中其他行的接近程度将聚类分配给记录。</li>
<li><code>integer ST_ClusterDBSCAN(geometry geom, float8 eps, integer minpoints)</code> 不需要指定多个簇。 一个划定距离，在这一距离内得几何将被划为一个族，，另外还有一个<code>minpoints</code>数，就是你希望一个聚类中最少的成员数</li>
</ul>
<p>这两种聚类窗口函数的使用示例：</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">SELECT</span> p<span class="token punctuation">.</span>pid<span class="token punctuation">,</span> p<span class="token punctuation">.</span>geom<span class="token punctuation">,</span>
    <span class="token keyword">COALESCE</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>addr_num <span class="token operator">||</span> <span class="token string">' '</span><span class="token punctuation">,</span><span class="token string">''</span><span class="token punctuation">)</span> <span class="token operator">||</span> full_str <span class="token keyword">AS</span> address<span class="token punctuation">,</span>
    ST_ClusterKMeans<span class="token punctuation">(</span>p<span class="token punctuation">.</span>geom<span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">)</span> <span class="token keyword">OVER</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> kcluster<span class="token punctuation">,</span> <span class="token comment">-- 分为4个聚类[0,3]</span>
    ST_ClusterDBSCAN<span class="token punctuation">(</span>p<span class="token punctuation">.</span>geom<span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span> <span class="token keyword">OVER</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> dcluster <span class="token comment">-- 最大距离为15米，每个聚类中至少有2个成员</span>
<span class="token keyword">FROM</span> ch09<span class="token punctuation">.</span>land <span class="token keyword">AS</span> p
<span class="token keyword">WHERE</span> ST_DWithin<span class="token punctuation">(</span>p<span class="token punctuation">.</span>geom<span class="token punctuation">,</span> 
      ST_GeomFromText<span class="token punctuation">(</span><span class="token string">'POINT(233110 900676)'</span><span class="token punctuation">,</span> <span class="token number">26986</span><span class="token punctuation">)</span><span class="token punctuation">,</span> 
<span class="token number">500</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><p>在这两种情况下，选择的指标会产生大约四个聚类</p>
<p><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b28ebc1200df47e5810e57df73434dc1~tplv-k3u1fbpfcp-zoom-1.image" alt="在这里插入图片描述"></p>
<p><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/e547f993042f49699b5916886a0e8776~tplv-k3u1fbpfcp-zoom-1.image" alt="在这里插入图片描述"></p>
<p><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/c8b9f6862cb5496aa827c9d8c03ad00b~tplv-k3u1fbpfcp-zoom-1.image" alt="在这里插入图片描述">****</p>
</template>
